services:
  - type: web
    name: fbm-sniper-community
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true